# Generated by Django 5.0.6 on 2024-06-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HatActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hat_api.genericcompletedvotabletask')),
            ],
        ),
    ]
