# Generated by Django 5.0.6 on 2024-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat_api', '0002_hattext_upvotes_alter_hattext_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCompletedVotableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='hattext',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hattext',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
