# Generated by Django 5.0.6 on 2024-06-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hat_api', '0002_hatactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HatActivity',
        ),
    ]
