# Generated by Django 5.0.6 on 2024-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hat_api', '0003_genericcompletedvotabletask_hattext_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hattext',
            name='text',
            field=models.CharField(max_length=8),
        ),
    ]
